### ISSUE TITLE
Help HTTP over TCP TUNNEL.

### ISSUE THREAD

**Issue by ingnelson** [moriyoshi/devproxy#19]
Hello @moriyoshi 

i am from America, it is possible with your knowledge create a HTTP over TCP tunnel to bypass my isp provider on GO ? 
because HTTPS or TLS or SSL is blocks by my ISP provider.

i think it is difficul for me .
i did all the test to check the isp restrictions.

my telegram is : @Trader_Nelson

i will wait your response.

**Comment by moriyoshi** [comment]
Sorry for the delay, but honestly I couldn't get it... If your ISP is really blocking your TLS traffics, how could you get to GitHub in the first place? Why haven't you tried changing the ISP?  Anyways, my software doesn't have a use for making a tunnel between your local and somewhere you can freely breath, so I'm going to close this issue...  It'd be good for you to take a look at usage of commands like netcat/socat.
